"""add_case_dicom_path

Revision ID: 1c9de23cb9af
Revises: bf48eccdf228
Create Date: 2026-07-09 20:00:56.693095
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


revision: str = '1c9de23cb9af'
down_revision: Union[str, None] = 'bf48eccdf228'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cases', sa.Column('dicom_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cases', 'dicom_path')
    # ### end Alembic commands ###
