"""initial

Revision ID: bf48eccdf228
Revises: 
Create Date: 2026-07-09 18:50:14.554091
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

revision: str = 'bf48eccdf228'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ts', sa.DateTime(), nullable=False),
    sa.Column('actor', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('entity_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('entity_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('payload_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('prev_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('immudb_tx_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cases',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('pseudonym', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('orthanc_study_uid', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sa.Enum('created', 'series_pending', 'series_confirmed', 'recipe_pending', 'recipe_confirmed', 'queued', 'running', 'review_ready', 'adjudicated', 'mdt_promoted', 'archived', 'blocked', 'failed', name='casestatus'), nullable=False),
    sa.Column('workup', sa.Enum('fcd', 'hs', 'both', name='workup'), nullable=True),
    sa.Column('contraindications', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cases_orthanc_study_uid'), 'cases', ['orthanc_study_uid'], unique=False)
    op.create_table('recipes',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('case_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('workup', sa.Enum('fcd', 'hs', 'both', name='workup'), nullable=False),
    sa.Column('spec', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recipes_case_id'), 'recipes', ['case_id'], unique=False)
    op.create_table('series',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('case_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('orthanc_series_uid', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('series_description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('modality', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('proposed_role', sa.Enum('t1_uni', 't1_inv1', 't1_inv2', 't1_mprage', 'flair', 't2', 'unknown', name='seriesrole'), nullable=False),
    sa.Column('confirmed_role', sa.Enum('t1_uni', 't1_inv1', 't1_inv2', 't1_mprage', 'flair', 't2', 'unknown', name='seriesrole'), nullable=True),
    sa.Column('image_type', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('geometry', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_series_case_id'), 'series', ['case_id'], unique=False)
    op.create_table('runs',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('case_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('recipe_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('detector_id', sa.Enum('meld_fcd', 'map', 'hippunfold', 'qt2', 'aid_hs', name='detectorid'), nullable=False),
    sa.Column('detector_version', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('source_role', sa.Enum('t1_uni', 't1_inv1', 't1_inv2', 't1_mprage', 'flair', 't2', 'unknown', name='seriesrole'), nullable=True),
    sa.Column('source_series_uid', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('status', sa.Enum('created', 'queued', 'preprocessing', 'qc_pending', 'inference', 'packaging', 'review_ready', 'adjudicated', 'failed', 'failed_oom', 'blocked', 'pending', name='runstatus'), nullable=False),
    sa.Column('device', sa.Enum('gpu', 'cpu', name='device'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('superseded_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ),
    sa.ForeignKeyConstraint(['superseded_by'], ['runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_runs_case_id'), 'runs', ['case_id'], unique=False)
    op.create_index(op.f('ix_runs_recipe_id'), 'runs', ['recipe_id'], unique=False)
    op.create_table('adjudications',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('run_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('reviewer', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ts', sa.DateTime(), nullable=False),
    sa.Column('agree', sa.Boolean(), nullable=True),
    sa.Column('confidence', sa.Integer(), nullable=True),
    sa.Column('ground_truth', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('supersedes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.ForeignKeyConstraint(['supersedes'], ['adjudications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_adjudications_run_id'), 'adjudications', ['run_id'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('run_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('stage', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('device', sa.Enum('gpu', 'cpu', name='device'), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('workdir', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_run_id'), 'jobs', ['run_id'], unique=False)
    op.create_table('provenance',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('run_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('os_checksum', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('image_digests', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('tool_versions', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('git_sha', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('input_series_uid', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('recon_provenance', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_provenance_run_id'), 'provenance', ['run_id'], unique=False)
    op.create_table('results',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('run_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('orthanc_t1_uid', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('orthanc_seg_uid', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('orthanc_probmap_uid', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('report_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('harmo_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('n_clusters', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_results_run_id'), 'results', ['run_id'], unique=False)
    op.create_table('clusters',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('result_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('hemi', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('location', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('size', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('saliency', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.ForeignKeyConstraint(['result_id'], ['results.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clusters_result_id'), 'clusters', ['result_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_clusters_result_id'), table_name='clusters')
    op.drop_table('clusters')
    op.drop_index(op.f('ix_results_run_id'), table_name='results')
    op.drop_table('results')
    op.drop_index(op.f('ix_provenance_run_id'), table_name='provenance')
    op.drop_table('provenance')
    op.drop_index(op.f('ix_jobs_run_id'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_adjudications_run_id'), table_name='adjudications')
    op.drop_table('adjudications')
    op.drop_index(op.f('ix_runs_recipe_id'), table_name='runs')
    op.drop_index(op.f('ix_runs_case_id'), table_name='runs')
    op.drop_table('runs')
    op.drop_index(op.f('ix_series_case_id'), table_name='series')
    op.drop_table('series')
    op.drop_index(op.f('ix_recipes_case_id'), table_name='recipes')
    op.drop_table('recipes')
    op.drop_index(op.f('ix_cases_orthanc_study_uid'), table_name='cases')
    op.drop_table('cases')
    op.drop_table('audit')
    # PostgreSQL enum types outlive their tables; dropping them makes a full downgrade/re-upgrade
    # deterministic for disaster-recovery and migration rehearsal environments.
    bind = op.get_bind()
    if bind.dialect.name == "postgresql":
        for enum_name in (
            "device", "runstatus", "detectorid", "seriesrole", "workup", "casestatus"
        ):
            postgresql.ENUM(name=enum_name).drop(bind, checkfirst=True)
    # ### end Alembic commands ###
